version: '3.7'
services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSSQL_DATABASE=db
      - MYSSQL_USER=app
      - MYSSQL_PASSWORD=pass